apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: aggrovites
  name: aggrovites
  namespace: aggrovites
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggrovites
  strategy:
    rollingUpdate:
      maxSurge: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: aggrovites
    spec:
      containers:
      - env:
        - name: MSSQL_DSN
          valueFrom:
            secretKeyRef:
              key: MSSQL_DSN
              name: aggrovites
        image: paulgmiller/aggrovites:ecd9699
        imagePullPolicy: Always
        name: letsmeetup
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 50m
            memory: 300Mi